version: 2.1
# https://github.com/AtomLinter/atom-linter-perlcritic/blob/master/.circleci/config.yml

jobs:
  perl-tests:
    docker:
      - image: cimg/base:stable
    environment:
      PERL_LWP_SSL_VERIFY_HOSTNAME: 0
    steps:
      - checkout
      - run:
          name: "Platform check"
          command: "uname -a"
      - run:
          name: "Setup apt packages"
          command: |
            sudo apt-get update
            sudo apt-get install --assume-yes --quiet       \
              --no-install-suggests --no-install-recommends \
              perl liblocal-lib-perl cpanminus libdevel-cover-perl
      - run:
          name: "Perl version check"
          command: |
            perl -v
      - run:
          name: "Setup local::lib"
          command: |
            echo 'eval "$(perl -I$HOME/perl5/lib/perl5 -Mlocal::lib)"' >> $BASH_ENV
      - run:
          name: "Install cpanm and multiple modules"
          command: |
            cpanm --notest --local-lib IO::Socket::SSL App::Cpan HTTP::Tiny
            cpan -I -M https://www.cpan.org -T ExtUtils::MakeMaker Test::Manifest
      - run:
          name: "Install dependencies"
          command: |
            cpan -I -M https://www.cpan.org -T .
      - run:
          name: "Run tests"
          command: |
            perl Makefile.PL
            make test
      - run:
          name: "Run author tests"
          command: |
            cpan -I -M https://www.cpan.org -T Test::CPAN::Changes
            prove -r -b xt
      - run:
          name: "Run parallel tests"
          command: |
            perl Makefile.PL
            HARNESS_OPTIONS=j10 make test
      - run:
          name: "Run dist tests"
          command: |
            perl Makefile.PL
            make disttest
            make clean
      - run:
          name: "Run coverage tests"
          command: |
            cpan -I -M https://www.cpan.org -T Devel::Cover::Report::Coveralls
            perl Makefile.PL
            cover -test -report coveralls

workflows:
  perl-workflow:
    jobs:
      - perl-tests:
          context:
            - business-isbn
