version: 2.1

aliases:
  - &common_job_stuff
    - docker:
      - image: cimg/base:stable
    - environment:
      PERL_LWP_SSL_VERIFY_HOSTNAME: 0

workflows:
  master:
    jobs:
      - "Checkout"
      - "Platform Check"
      - "apt-get stuff":
      - "Perl Version Check"
        requires: "apt-get stuff"
      - "Setup local::lib":
        requires: "apt-get stuff"
      - "Install Perl modules":
        requires: "Setup local::lib"
      - "Install dependencies":
        requires: "Install Perl modules"
      - "Normal tests":
        requires: "Install dependencies"
      - "Author tests":
        requires: "Install dependencies"
      - "Parallel tests":
        requires: "Install dependencies"
      - "Dist tests":
        requires: "Install dependencies"
      - "Coverage tests":
        requires: "Install dependencies"

jobs:
  "Checkout":
    <<: *common_job_stuff
    steps:
      - checkout
  "Platform Check":
    <<: *common_job_stuff
    steps:
      - uname -a
  "apt-get stuff":
    <<: *common_job_stuff
    steps:
      - run: |
          sudo apt-get update
          sudo apt-get install --assume-yes --quiet       \
            --no-install-suggests --no-install-recommends \
            perl liblocal-lib-perl cpanminus libdevel-cover-perl
  "Perl Version Check":
    <<: *common_job_stuff
    steps:
      - perl -v
  "Setup local::lib":
    <<: *common_job_stuff
    steps:
      - echo 'eval "$(perl -I$HOME/perl5/lib/perl5 -Mlocal::lib)"' >> $BASH_ENV
  "Install Perl modules":
    <<: *common_job_stuff
    steps:
      - run: |
          cpanm --notest --local-lib IO::Socket::SSL App::Cpan HTTP::Tiny
          cpan -I -M https://www.cpan.org -T ExtUtils::MakeMaker Test::Manifest
  "Install dependencies":
    <<: *common_job_stuff
    steps:
      - cpan -I -M https://www.cpan.org -T .
  "Normal tests":
    <<: *common_job_stuff
    steps:
      - run: |
          perl Makefile.PL
          make test
  "Author tests":
    <<: *common_job_stuff
    steps:
      - run: |
          cpan -I -M https://www.cpan.org -T Test::CPAN::Changes
          prove -r -b xt
  "Parallel tests":
    <<: *common_job_stuff
    steps:
      - run: |
          perl Makefile.PL
          HARNESS_OPTIONS=j10 make test
  "Dist tests":
    <<: *common_job_stuff
    steps:
      - run: |
          perl Makefile.PL
          make disttest
          make clean
  "Coverage tests":
    <<: *common_job_stuff
    steps:
      - run: |
          cpan -I -M https://www.cpan.org -T Devel::Cover::Report::Coveralls
          perl Makefile.PL
          cover -test -report coveralls

