version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: "Platform check"
          command: "uname -a"
      - run:
          name: "Perl version check"
          command: "perl -v"

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
